package:
  name: widgetron
  version: 1

source:
  git_url: https://github.com/JoelStansbury/widgetron.git

build:
  number: 0
  script: python -m pip install ./src

requirements:
  host:
    - python
    - pip

  run:
    - python
    - jinja2
    - constructor
    - nsis
    - boa

test:
  imports:
    - widgetron