name: dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - black
  - boa
  - constructor >=3.3, <3.4
  - flit >=3.9.0, <4
  - isort
  - jupyterlab >=3, <4
  - nodejs >=18, <19
  - python >=3.9, <3.12
  - pyyaml
  - tomli