name: dev

channels:
  - conda-forge
  # - main  # Uncomment if using osx-arm64 install of python

dependencies:
  - python <=3.11
  - constructor <4
  - boa
  - nodejs >18, <19
  - jupyterlab >3, <4
  - black
  - isort