name: dev

channels:
  - conda-forge
  # - main  # Uncomment if using osx-arm64 install of python

dependencies:
  - python
  - constructor<3.4
  - boa
  - nodejs
  - jupyterlab
  - black
  - isort