name: dev

channels:
  - conda-forge

dependencies:
  - python <=3.11
  - constructor >=3.3, <4
  - boa
  - nodejs >18, <19
  - yarn >=1, <2
  - jupyterlab >3, <4
  - yaml
  - black
  - isort
