name: dev

channels:
  - conda-forge
  # - main  # Uncomment if using osx-arm64 install of python

dependencies:
  - python <=3.11
  - jupyterlab >3, <4
  - conda
  - menuinst >=1.4.17
  - ipywidgets