
[tool.widgetron]
notebook = "App Name"
version = "0.1.0"
window_style = "Normal"
outdir = "output"
license_file = "LICENSE"
install_path = "c:/WTronExamples/App_Name"
explicit_lock = "conda-linux-64.lock"
skip_sbom = true
post_install = "post_install.sh"