
[tool.widgetron]
notebook = "Minesweeper.ipynb"
explicit_lock = "conda-linux-64.lock"
server_command = ["jupyter", "lab", "--no-browser"]
version = "0.1.0"
license_file = "LICENSE"
installer_filename = "Minesweeper_Installer.exe"
welcome_image = "assets/welcome_image.png"
header_image_text = "header text"
install_path = "c:/a/Minesweeper"
skip_sbom = true
# domain_whitelist = ["www.google.com", "github.com"]
# url_whitelist = ["https://github.com/JoelStansbury/widgetron/"]