name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: dev
        environment-file: environment.yml

    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]

    - name: Package the extension
      run: |
        set -eux

        pip install build
        python -m build

    - name: Upload extension packages
      uses: actions/upload-artifact@v3
      with:
        name: extension-artifacts
        path: dist/*
        if-no-files-found: error
