name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: dev
        use-mamba: true

    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - uses: actions/cache@v2
      with:
        path: ${{ matrix.prefix }}
        key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: cache

    - name: Update Environment
      run: mamba env update -n dev -f environment.yml
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Test
      run: |
        mkdir dist
        python -m pip install . --no-build-isolation
        widgetron -h
        widgetron -dir=examples/minesweeper -o=dist

    - name: Package
      run: |
        set -eux

        pip install build
        python -m build
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-artifacts
        path: dist/*
        if-no-files-found: error
