name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        # - os: macos-latest
        #   path: ~/Library/Caches/pip
        # - os: windows-latest
        #   path: ~\AppData\Local\pip\Cache

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: environment.yml
          use-mamba: true

      - run: conda list

      - name: Test
        run: |
          mkdir dist
          python -m pip install . --no-build-isolation
          widgetron -h
          widgetron examples/minesweeper -o=dist

      - name: Package
        run: |
          set -eux

          pip install build
          python -m build
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extension-artifacts
          path: dist/*
          if-no-files-found: error
